services:
  csharp-todo-db:
    image: postgres:16.3-alpine
    container_name: csharp-todo-db
    hostname: csharp-todo-db
    environment:
      - POSTGRES_USER=todoapi
      - POSTGRES_PASSWORD=em4xooNu
      - POSTGRES_DB=todo
    volumes:
      - csharp_todo_db_postgress_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  csharp_todo_db_postgress_data:
