version: '3.8'

services:
  csharp-todo-db:
    image: mcr.microsoft.com/mssql/server:2019-CU27-ubuntu-20.04
    container_name: csharp-todo-db
    hostname: csharp-todo-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Buquaem6
      - MSSQL_COLLATION=LATIN1_GENERAL_100_CI_AS_SC_UTF8
    volumes:
      - csharp_todo_db_data:/var/opt/mssql/
      - $PWD/docker/scripts/:/App/scripts/
    ports:
      - 127.0.0.1:1433:1433

volumes:
  csharp_todo_db_data:
