USE [todo]
GO

IF OBJECT_ID('TodoItems', 'U') IS NULL
CREATE TABLE TodoItems (
    Id INT IDENTITY(1, 1),
    Title NVARCHAR(100) NOT NULL,
    IsComplete BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (Id)
)
GO
